name: uas_capstone
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.0.5
  shared_preferences: ^2.2.0
  intl: ^0.18.1

  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.3
  path: ^1.9.0

  image_picker: ^1.0.7
  fl_chart: ^0.65.0

  flutter_local_notifications: ^17.2.2
  timezone: ^0.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.3.10
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo512.jpg

# ===============================
# SPLASH SCREEN CONFIGURATION
# ===============================
flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/logo512.jpg

  android_12:
    image: assets/images/logo512.jpg
    color: "#FFFFFF"

  android: true
  ios: true
  web: false
  fullscreen: true

flutter_launcher_icons:
  android: true
  ios: true

  windows:
    generate: true
    image_path: assets/images/logo512.jpg

  image_path: assets/images/logo512.jpg
  min_sdk_android: 21
